name: Test valgrind

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: r-package/balnet

    steps:
      - uses: actions/checkout@v4

      - name: Setup valgrind
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq valgrind

      - name: Setup R
        run: |
          curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap
          ./run.sh install_all
          R CMD INSTALL .

      - name: Test
        run: |
          R -d "valgrind --tool=memcheck --leak-check=full --error-exitcode=1" --vanilla < tests/valgrind/test_valgrind.R
